# https://travis-ci.org/#!/translate/translate
language: python
python:
  - 2.6
  - 2.7
  #- pypy - nice to try once lxml is supported or we can switch lxml off
env:
  - USECPO=0
  #- USECPO=1
  #- USECPO=2
install:
  - sudo apt-get install python-aeidon
  - pip install --use-mirrors -r requirements/dev.txt
  # Still need to handle with indexing engines
script:
  - py.test -r EfsxX
notifications:
  email:
    on_failure: always
    on_success: change
